package me.andre111.mambience.util;

import org.bukkit.Material;

public class MaterialNameUtil {
	public static String getInternalName(Material mat) {
		switch(mat) {
		case ACACIA_DOOR:
			return "minecraft:acacia_door";
		case ACACIA_DOOR_ITEM:
			return "minecraft:acacia_door";
		case ACACIA_FENCE:
			return "minecraft:acacia_fence";
		case ACACIA_FENCE_GATE:
			return "minecraft:acacia_fence_gate";
		case ACACIA_STAIRS:
			return "minecraft:acacia_stairs";
		case ACTIVATOR_RAIL:
			return "minecraft:activator_rail";
		case AIR:
			return "minecraft:air";
		case ANVIL:
			return "minecraft:anvil";
		case APPLE:
			return "minecraft:apple";
		case ARMOR_STAND:
			return "minecraft:armor_stand";
		case ARROW:
			return "minecraft:arrow";
		case BAKED_POTATO:
			return "minecraft:baked_potato";
		case BANNER:
			return "minecraft:banner";
		case BARRIER:
			return "minecraft:barrier";
		case BEACON:
			return "minecraft:beacon";
		case BED:
			return "minecraft:bed";
		case BEDROCK:
			return "minecraft:bedrock";
		case BED_BLOCK:
			return "minecraft:bed";
		case BEETROOT:
			return "minecraft:beetroot";
		case BEETROOT_BLOCK:
			return "minecraft:beetroots";
		case BEETROOT_SEEDS:
			return "minecraft:beetroot_seeds";
		case BEETROOT_SOUP:
			return "minecraft:beetroot_soup";
		case BIRCH_DOOR:
			return "minecraft:birch_door";
		case BIRCH_DOOR_ITEM:
			return "minecraft:birch_door";
		case BIRCH_FENCE:
			return "minecraft:birch_fence";
		case BIRCH_FENCE_GATE:
			return "minecraft:birch_fence_gate";
		case BIRCH_WOOD_STAIRS:
			return "minecraft:birch_stairs";
		case BLACK_SHULKER_BOX:
			return "minecraft:black_shulker_box";
		case BLAZE_POWDER:
			return "minecraft:blaze_powder";
		case BLAZE_ROD:
			return "minecraft:blaze_rod";
		case BLUE_SHULKER_BOX:
			return "minecraft:blue_shulker_box";
		case BOAT:
			return "minecraft:boat";
		case BOAT_ACACIA:
			return "minecraft:acacia_boat";
		case BOAT_BIRCH:
			return "minecraft:birch_boat";
		case BOAT_DARK_OAK:
			return "minecraft:dark_oak_boat";
		case BOAT_JUNGLE:
			return "minecraft:jungle_boat";
		case BOAT_SPRUCE:
			return "minecraft:spruce_boat";
		case BONE:
			return "minecraft:bone";
		case BONE_BLOCK:
			return "minecraft:bone_block";
		case BOOK:
			return "minecraft:book";
		case BOOKSHELF:
			return "minecraft:bookshelf";
		case BOOK_AND_QUILL:
			return "minecraft:writable_book";
		case BOW:
			return "minecraft:bow";
		case BOWL:
			return "minecraft:bowl";
		case BREAD:
			return "minecraft:bread";
		case BREWING_STAND:
			return "minecraft:brewing_stand";
		case BREWING_STAND_ITEM:
			return "minecraft:brewing_stand";
		case BRICK:
			return "minecraft:brick_block";
		case BRICK_STAIRS:
			return "minecraft:brick_stairs";
		case BROWN_MUSHROOM:
			return "minecraft:brown_mushroom";
		case BROWN_SHULKER_BOX:
			return "minecraft:brown_shulker_box";
		case BUCKET:
			return "minecraft:bucket";
		case BURNING_FURNACE:
			return "minecraft:lit_furnace";
		case CACTUS:
			return "minecraft:cactus";
		case CAKE:
			return "minecraft:cake";
		case CAKE_BLOCK:
			return "minecraft:cake";
		case CARPET:
			return "minecraft:carpet";
		case CARROT:
			return "minecraft:carrots";
		case CARROT_ITEM:
			return "minecraft:carrot";
		case CARROT_STICK:
			return "minecraft:carrot_on_a_stick";
		case CAULDRON:
			return "minecraft:cauldron";
		case CAULDRON_ITEM:
			return "minecraft:cauldron";
		case CHAINMAIL_BOOTS:
			return "minecraft:chainmail_boots";
		case CHAINMAIL_CHESTPLATE:
			return "minecraft:chainmail_chestplate";
		case CHAINMAIL_HELMET:
			return "minecraft:chainmail_helmet";
		case CHAINMAIL_LEGGINGS:
			return "minecraft:chainmail_leggings";
		case CHEST:
			return "minecraft:chest";
		case CHORUS_FLOWER:
			return "minecraft:chorus_flower";
		case CHORUS_FRUIT:
			return "minecraft:chorus_fruit";
		case CHORUS_FRUIT_POPPED:
			return "minecraft:chorus_fruit_popped";
		case CHORUS_PLANT:
			return "minecraft:chorus_plant";
		case CLAY:
			return "minecraft:clay";
		case CLAY_BALL:
			return "minecraft:clay_ball";
		case CLAY_BRICK:
			return "minecraft:brick";
		case COAL:
			return "minecraft:coal";
		case COAL_BLOCK:
			return "minecraft:coal_block";
		case COAL_ORE:
			return "minecraft:coal_ore";
		case COBBLESTONE:
			return "minecraft:cobblestone";
		case COBBLESTONE_STAIRS:
			return "minecraft:stone_stairs";
		case COBBLE_WALL:
			return "minecraft:cobblestone_wall";
		case COCOA:
			return "minecraft:cocoa";
		case COMMAND:
			return "minecraft:command_block";
		case COMMAND_CHAIN:
			return "minecraft:chain_command_block";
		case COMMAND_MINECART:
			return "minecraft:command_block_minecart";
		case COMMAND_REPEATING:
			return "minecraft:repeating_command_block";
		case COMPASS:
			return "minecraft:compass";
		case COOKED_BEEF:
			return "minecraft:cooked_beef";
		case COOKED_CHICKEN:
			return "minecraft:cooked_chicken";
		case COOKED_FISH:
			return "minecraft:cooked_fish";
		case COOKED_MUTTON:
			return "minecraft:cooked_mutton";
		case COOKED_RABBIT:
			return "minecraft:cooked_rabbit";
		case COOKIE:
			return "minecraft:cookie";
		case CROPS:
			return "minecraft:wheat";
		case CYAN_SHULKER_BOX:
			return "minecraft:cyan_shulker_box";
		case DARK_OAK_DOOR:
			return "minecraft:dark_oak_door";
		case DARK_OAK_DOOR_ITEM:
			return "minecraft:dark_oak_door";
		case DARK_OAK_FENCE:
			return "minecraft:dark_oak_fence";
		case DARK_OAK_FENCE_GATE:
			return "minecraft:dark_oak_fence_gate";
		case DARK_OAK_STAIRS:
			return "minecraft:dark_oak_stairs";
		case DAYLIGHT_DETECTOR:
			return "minecraft:daylight_detector";
		case DAYLIGHT_DETECTOR_INVERTED:
			return "minecraft:daylight_detector_inverted";
		case DEAD_BUSH:
			return "minecraft:deadbush";
		case DETECTOR_RAIL:
			return "minecraft:detector_rail";
		case DIAMOND:
			return "minecraft:diamond";
		case DIAMOND_AXE:
			return "minecraft:diamond_axe";
		case DIAMOND_BARDING:
			return "minecraft:diamond_horse_armor";
		case DIAMOND_BLOCK:
			return "minecraft:diamond_block";
		case DIAMOND_BOOTS:
			return "minecraft:diamond_boots";
		case DIAMOND_CHESTPLATE:
			return "minecraft:diamond_chestplate";
		case DIAMOND_HELMET:
			return "minecraft:diamond_helmet";
		case DIAMOND_HOE:
			return "minecraft:diamond_hoe";
		case DIAMOND_LEGGINGS:
			return "minecraft:diamond_leggings";
		case DIAMOND_ORE:
			return "minecraft:diamond_ore";
		case DIAMOND_PICKAXE:
			return "minecraft:diamond_pickaxe";
		case DIAMOND_SPADE:
			return "minecraft:diamond_shovel";
		case DIAMOND_SWORD:
			return "minecraft:diamond_sword";
		case DIODE:
			return "minecraft:repeater";
		case DIODE_BLOCK_OFF:
			return "minecraft:unpowered_repeater";
		case DIODE_BLOCK_ON:
			return "minecraft:powered_repeater";
		case DIRT:
			return "minecraft:dirt";
		case DISPENSER:
			return "minecraft:dispenser";
		case DOUBLE_PLANT:
			return "minecraft:double_plant";
		case DOUBLE_STEP:
			return "minecraft:double_stone_slab";
		case DOUBLE_STONE_SLAB2:
			return "minecraft:double_stone_slab2";
		case DRAGONS_BREATH:
			return "minecraft:dragon_breath";
		case DRAGON_EGG:
			return "minecraft:dragon_egg";
		case DROPPER:
			return "minecraft:dropper";
		case EGG:
			return "minecraft:egg";
		case ELYTRA:
			return "minecraft:elytra";
		case EMERALD:
			return "minecraft:emerald";
		case EMERALD_BLOCK:
			return "minecraft:emerald_block";
		case EMERALD_ORE:
			return "minecraft:emerald_ore";
		case EMPTY_MAP:
			return "minecraft:map";
		case ENCHANTED_BOOK:
			return "minecraft:enchanted_book";
		case ENCHANTMENT_TABLE:
			return "minecraft:enchanting_table";
		case ENDER_CHEST:
			return "minecraft:ender_chest";
		case ENDER_PEARL:
			return "minecraft:ender_pearl";
		case ENDER_PORTAL:
			return "minecraft:end_portal";
		case ENDER_PORTAL_FRAME:
			return "minecraft:end_portal_frame";
		case ENDER_STONE:
			return "minecraft:end_stone";
		case END_BRICKS:
			return "minecraft:end_bricks";
		case END_CRYSTAL:
			return "minecraft:end_crystal";
		case END_GATEWAY:
			return "minecraft:end_gateway";
		case END_ROD:
			return "minecraft:end_rod";
		case EXPLOSIVE_MINECART:
			return "minecraft:tnt_minecart";
		case EXP_BOTTLE:
			return "minecraft:experience_bottle";
		case EYE_OF_ENDER:
			return "minecraft:ender_eye";
		case FEATHER:
			return "minecraft:feather";
		case FENCE:
			return "minecraft:fence";
		case FENCE_GATE:
			return "minecraft:fence_gate";
		case FERMENTED_SPIDER_EYE:
			return "minecraft:fermented_spider_eye";
		case FIRE:
			return "minecraft:fire";
		case FIREBALL:
			return "minecraft:fire_charge";
		case FIREWORK:
			return "minecraft:fireworks";
		case FIREWORK_CHARGE:
			return "minecraft:firework_charge";
		case FISHING_ROD:
			return "minecraft:fishing_rod";
		case FLINT:
			return "minecraft:flint";
		case FLINT_AND_STEEL:
			return "minecraft:flint_and_steel";
		case FLOWER_POT:
			return "minecraft:flower_pot";
		case FLOWER_POT_ITEM:
			return "minecraft:flower_pot";
		case FROSTED_ICE:
			return "minecraft:frosted_ice";
		case FURNACE:
			return "minecraft:furnace";
		case GHAST_TEAR:
			return "minecraft:ghast_tear";
		case GLASS:
			return "minecraft:glass";
		case GLASS_BOTTLE:
			return "minecraft:glass_bottle";
		case GLOWING_REDSTONE_ORE:
			return "minecraft:lit_redstone_ore";
		case GLOWSTONE:
			return "minecraft:glowstone";
		case GLOWSTONE_DUST:
			return "minecraft:glowstone_dust";
		case GOLDEN_APPLE:
			return "minecraft:golden_apple";
		case GOLDEN_CARROT:
			return "minecraft:golden_carrot";
		case GOLD_AXE:
			return "minecraft:golden_axe";
		case GOLD_BARDING:
			return "minecraft:golden_horse_armor";
		case GOLD_BLOCK:
			return "minecraft:gold_block";
		case GOLD_BOOTS:
			return "minecraft:golden_boots";
		case GOLD_CHESTPLATE:
			return "minecraft:golden_chestplate";
		case GOLD_HELMET:
			return "minecraft:golden_helmet";
		case GOLD_HOE:
			return "minecraft:golden_hoe";
		case GOLD_INGOT:
			return "minecraft:gold_ingot";
		case GOLD_LEGGINGS:
			return "minecraft:golden_leggings";
		case GOLD_NUGGET:
			return "minecraft:gold_nugget";
		case GOLD_ORE:
			return "minecraft:gold_ore";
		case GOLD_PICKAXE:
			return "minecraft:golden_pickaxe";
		case GOLD_PLATE:
			return "minecraft:light_weighted_pressure_plate";
		case GOLD_RECORD:
			return "minecraft:record_13";
		case GOLD_SPADE:
			return "minecraft:golden_shovel";
		case GOLD_SWORD:
			return "minecraft:golden_sword";
		case GRASS:
			return "minecraft:grass";
		case GRASS_PATH:
			return "minecraft:grass_path";
		case GRAVEL:
			return "minecraft:gravel";
		case GRAY_SHULKER_BOX:
			return "minecraft:gray_shulker_box";
		case GREEN_RECORD:
			return "minecraft:record_cat";
		case GREEN_SHULKER_BOX:
			return "minecraft:green_shulker_box";
		case GRILLED_PORK:
			return "minecraft:cooked_porkchop";
		case HARD_CLAY:
			return "minecraft:hardened_clay";
		case HAY_BLOCK:
			return "minecraft:hay_block";
		case HOPPER:
			return "minecraft:hopper";
		case HOPPER_MINECART:
			return "minecraft:hopper_minecart";
		case HUGE_MUSHROOM_1:
			return "minecraft:brown_mushroom_block";
		case HUGE_MUSHROOM_2:
			return "minecraft:red_mushroom_block";
		case ICE:
			return "minecraft:ice";
		case INK_SACK:
			return "minecraft:dye";
		case IRON_AXE:
			return "minecraft:iron_axe";
		case IRON_BARDING:
			return "minecraft:iron_horse_armor";
		case IRON_BLOCK:
			return "minecraft:iron_block";
		case IRON_BOOTS:
			return "minecraft:iron_boots";
		case IRON_CHESTPLATE:
			return "minecraft:iron_chestplate";
		case IRON_DOOR:
			return "minecraft:iron_door";
		case IRON_DOOR_BLOCK:
			return "minecraft:iron_door";
		case IRON_FENCE:
			return "minecraft:iron_bars";
		case IRON_HELMET:
			return "minecraft:iron_helmet";
		case IRON_HOE:
			return "minecraft:iron_hoe";
		case IRON_INGOT:
			return "minecraft:iron_ingot";
		case IRON_LEGGINGS:
			return "minecraft:iron_leggings";
		case IRON_NUGGET:
			return "minecraft:iron_nugget";
		case IRON_ORE:
			return "minecraft:iron_ore";
		case IRON_PICKAXE:
			return "minecraft:iron_pickaxe";
		case IRON_PLATE:
			return "minecraft:heavy_weighted_pressure_plate";
		case IRON_SPADE:
			return "minecraft:iron_shovel";
		case IRON_SWORD:
			return "minecraft:iron_sword";
		case IRON_TRAPDOOR:
			return "minecraft:iron_trapdoor";
		case ITEM_FRAME:
			return "minecraft:item_frame";
		case JACK_O_LANTERN:
			return "minecraft:lit_pumpkin";
		case JUKEBOX:
			return "minecraft:jukebox";
		case JUNGLE_DOOR:
			return "minecraft:jungle_door";
		case JUNGLE_DOOR_ITEM:
			return "minecraft:jungle_door";
		case JUNGLE_FENCE:
			return "minecraft:jungle_fence";
		case JUNGLE_FENCE_GATE:
			return "minecraft:jungle_fence_gate";
		case JUNGLE_WOOD_STAIRS:
			return "minecraft:jungle_stairs";
		case LADDER:
			return "minecraft:ladder";
		case LAPIS_BLOCK:
			return "minecraft:lapis_block";
		case LAPIS_ORE:
			return "minecraft:lapis_ore";
		case LAVA:
			return "minecraft:flowing_lava";
		case LAVA_BUCKET:
			return "minecraft:lava_bucket";
		case LEASH:
			return "minecraft:lead";
		case LEATHER:
			return "minecraft:leather";
		case LEATHER_BOOTS:
			return "minecraft:leather_boots";
		case LEATHER_CHESTPLATE:
			return "minecraft:leather_chestplate";
		case LEATHER_HELMET:
			return "minecraft:leather_helmet";
		case LEATHER_LEGGINGS:
			return "minecraft:leather_leggings";
		case LEAVES:
			return "minecraft:leaves";
		case LEAVES_2:
			return "minecraft:leaves2";
		case LEVER:
			return "minecraft:lever";
		case LIGHT_BLUE_SHULKER_BOX:
			return "minecraft:light_blue_shulker_box";
		case LIME_SHULKER_BOX:
			return "minecraft:lime_shulker_box";
		case LINGERING_POTION:
			return "minecraft:lingering_potion";
		case LOG:
			return "minecraft:log";
		case LOG_2:
			return "minecraft:log2";
		case LONG_GRASS:
			return "minecraft:tallgrass";
		case MAGENTA_SHULKER_BOX:
			return "minecraft:magenta_shulker_box";
		case MAGMA:
			return "minecraft:magma";
		case MAGMA_CREAM:
			return "minecraft:magma_cream";
		case MAP:
			return "minecraft:filled_map";
		case MELON:
			return "minecraft:melon";
		case MELON_BLOCK:
			return "minecraft:melon_block";
		case MELON_SEEDS:
			return "minecraft:melon_seeds";
		case MELON_STEM:
			return "minecraft:melon_stem";
		case MILK_BUCKET:
			return "minecraft:milk_bucket";
		case MINECART:
			return "minecraft:minecart";
		case MOB_SPAWNER:
			return "minecraft:mob_spawner";
		case MONSTER_EGG:
			return "minecraft:spawn_egg";
		case MONSTER_EGGS:
			return "minecraft:monster_egg";
		case MOSSY_COBBLESTONE:
			return "minecraft:mossy_cobblestone";
		case MUSHROOM_SOUP:
			return "minecraft:mushroom_stew";
		case MUTTON:
			return "minecraft:mutton";
		case MYCEL:
			return "minecraft:mycelium";
		case NAME_TAG:
			return "minecraft:name_tag";
		case NETHERRACK:
			return "minecraft:netherrack";
		case NETHER_BRICK:
			return "minecraft:nether_brick";
		case NETHER_BRICK_ITEM:
			return "minecraft:netherbrick";
		case NETHER_BRICK_STAIRS:
			return "minecraft:nether_brick_stairs";
		case NETHER_FENCE:
			return "minecraft:nether_brick_fence";
		case NETHER_STALK:
			return "minecraft:nether_wart";
		case NETHER_STAR:
			return "minecraft:nether_star";
		case NETHER_WARTS:
			return "minecraft:nether_wart";
		case NETHER_WART_BLOCK:
			return "minecraft:nether_wart_block";
		case NOTE_BLOCK:
			return "minecraft:noteblock";
		case OBSERVER:
			return "minecraft:observer";
		case OBSIDIAN:
			return "minecraft:obsidian";
		case ORANGE_SHULKER_BOX:
			return "minecraft:orange_shulker_box";
		case PACKED_ICE:
			return "minecraft:packed_ice";
		case PAINTING:
			return "minecraft:painting";
		case PAPER:
			return "minecraft:paper";
		case PINK_SHULKER_BOX:
			return "minecraft:pink_shulker_box";
		case PISTON_BASE:
			return "minecraft:piston";
		case PISTON_EXTENSION:
			return "minecraft:piston_head";
		case PISTON_MOVING_PIECE:
			return "minecraft:piston_extension";
		case PISTON_STICKY_BASE:
			return "minecraft:sticky_piston";
		case POISONOUS_POTATO:
			return "minecraft:poisonous_potato";
		case PORK:
			return "minecraft:porkchop";
		case PORTAL:
			return "minecraft:portal";
		case POTATO:
			return "minecraft:potatoes";
		case POTATO_ITEM:
			return "minecraft:potato";
		case POTION:
			return "minecraft:potion";
		case POWERED_MINECART:
			return "minecraft:furnace_minecart";
		case POWERED_RAIL:
			return "minecraft:golden_rail";
		case PRISMARINE:
			return "minecraft:prismarine";
		case PRISMARINE_CRYSTALS:
			return "minecraft:prismarine_crystals";
		case PRISMARINE_SHARD:
			return "minecraft:prismarine_shard";
		case PUMPKIN:
			return "minecraft:pumpkin";
		case PUMPKIN_PIE:
			return "minecraft:pumpkin_pie";
		case PUMPKIN_SEEDS:
			return "minecraft:pumpkin_seeds";
		case PUMPKIN_STEM:
			return "minecraft:pumpkin_stem";
		case PURPLE_SHULKER_BOX:
			return "minecraft:purple_shulker_box";
		case PURPUR_BLOCK:
			return "minecraft:purpur_block";
		case PURPUR_DOUBLE_SLAB:
			return "minecraft:purpur_double_slab";
		case PURPUR_PILLAR:
			return "minecraft:purpur_pillar";
		case PURPUR_SLAB:
			return "minecraft:purpur_slab";
		case PURPUR_STAIRS:
			return "minecraft:purpur_stairs";
		case QUARTZ:
			return "minecraft:quartz";
		case QUARTZ_BLOCK:
			return "minecraft:quartz_block";
		case QUARTZ_ORE:
			return "minecraft:quartz_ore";
		case QUARTZ_STAIRS:
			return "minecraft:quartz_stairs";
		case RABBIT:
			return "minecraft:rabbit";
		case RABBIT_FOOT:
			return "minecraft:rabbit_foot";
		case RABBIT_HIDE:
			return "minecraft:rabbit_hide";
		case RABBIT_STEW:
			return "minecraft:rabbit_stew";
		case RAILS:
			return "minecraft:rail";
		case RAW_BEEF:
			return "minecraft:beef";
		case RAW_CHICKEN:
			return "minecraft:chicken";
		case RAW_FISH:
			return "minecraft:fish";
		case RECORD_10:
			return "minecraft:record_ward";
		case RECORD_11:
			return "minecraft:record_11";
		case RECORD_12:
			return "minecraft:record_wait";
		case RECORD_3:
			return "minecraft:record_blocks";
		case RECORD_4:
			return "minecraft:record_chirp";
		case RECORD_5:
			return "minecraft:record_far";
		case RECORD_6:
			return "minecraft:record_mall";
		case RECORD_7:
			return "minecraft:record_mellohi";
		case RECORD_8:
			return "minecraft:record_stal";
		case RECORD_9:
			return "minecraft:record_strad";
		case REDSTONE:
			return "minecraft:redstone";
		case REDSTONE_BLOCK:
			return "minecraft:redstone_block";
		case REDSTONE_COMPARATOR:
			return "minecraft:comparator";
		case REDSTONE_COMPARATOR_OFF:
			return "minecraft:unpowered_comparator";
		case REDSTONE_COMPARATOR_ON:
			return "minecraft:powered_comparator";
		case REDSTONE_LAMP_OFF:
			return "minecraft:redstone_lamp";
		case REDSTONE_LAMP_ON:
			return "minecraft:lit_redstone_lamp";
		case REDSTONE_ORE:
			return "minecraft:redstone_ore";
		case REDSTONE_TORCH_OFF:
			return "minecraft:unlit_redstone_torch";
		case REDSTONE_TORCH_ON:
			return "minecraft:redstone_torch";
		case REDSTONE_WIRE:
			return "minecraft:redstone_wire";
		case RED_MUSHROOM:
			return "minecraft:red_mushroom";
		case RED_NETHER_BRICK:
			return "minecraft:red_nether_brick";
		case RED_ROSE:
			return "minecraft:red_flower";
		case RED_SANDSTONE:
			return "minecraft:red_sandstone";
		case RED_SANDSTONE_STAIRS:
			return "minecraft:red_sandstone_stairs";
		case RED_SHULKER_BOX:
			return "minecraft:red_shulker_box";
		case ROTTEN_FLESH:
			return "minecraft:rotten_flesh";
		case SADDLE:
			return "minecraft:saddle";
		case SAND:
			return "minecraft:sand";
		case SANDSTONE:
			return "minecraft:sandstone";
		case SANDSTONE_STAIRS:
			return "minecraft:sandstone_stairs";
		case SAPLING:
			return "minecraft:sapling";
		case SEA_LANTERN:
			return "minecraft:sea_lantern";
		case SEEDS:
			return "minecraft:wheat_seeds";
		case SHEARS:
			return "minecraft:shears";
		case SHIELD:
			return "minecraft:shield";
		case SHULKER_SHELL:
			return "minecraft:shulker_shell";
		case SIGN:
			return "minecraft:sign";
		case SIGN_POST:
			return "minecraft:standing_sign";
		case SILVER_SHULKER_BOX:
			return "minecraft:silver_shulker_box";
		case SKULL:
			return "minecraft:skull";
		case SKULL_ITEM:
			return "minecraft:skull";
		case SLIME_BALL:
			return "minecraft:slime_ball";
		case SLIME_BLOCK:
			return "minecraft:slime";
		case SMOOTH_BRICK:
			return "minecraft:stonebrick";
		case SMOOTH_STAIRS:
			return "minecraft:stone_brick_stairs";
		case SNOW:
			return "minecraft:snow_layer";
		case SNOW_BALL:
			return "minecraft:snowball";
		case SNOW_BLOCK:
			return "minecraft:snow";
		case SOIL:
			return "minecraft:farmland";
		case SOUL_SAND:
			return "minecraft:soul_sand";
		case SPECKLED_MELON:
			return "minecraft:speckled_melon";
		case SPECTRAL_ARROW:
			return "minecraft:spectral_arrow";
		case SPIDER_EYE:
			return "minecraft:spider_eye";
		case SPLASH_POTION:
			return "minecraft:splash_potion";
		case SPONGE:
			return "minecraft:sponge";
		case SPRUCE_DOOR:
			return "minecraft:spruce_door";
		case SPRUCE_DOOR_ITEM:
			return "minecraft:spruce_door";
		case SPRUCE_FENCE:
			return "minecraft:spruce_fence";
		case SPRUCE_FENCE_GATE:
			return "minecraft:spruce_fence_gate";
		case SPRUCE_WOOD_STAIRS:
			return "minecraft:spruce_stairs";
		case STAINED_CLAY:
			return "minecraft:stained_hardened_clay";
		case STAINED_GLASS:
			return "minecraft:stained_glass";
		case STAINED_GLASS_PANE:
			return "minecraft:stained_glass_pane";
		case STANDING_BANNER:
			return "minecraft:standing_banner";
		case STATIONARY_LAVA:
			return "minecraft:lava";
		case STATIONARY_WATER:
			return "minecraft:water";
		case STEP:
			return "minecraft:stone_slab";
		case STICK:
			return "minecraft:stick";
		case STONE:
			return "minecraft:stone";
		case STONE_AXE:
			return "minecraft:stone_axe";
		case STONE_BUTTON:
			return "minecraft:stone_button";
		case STONE_HOE:
			return "minecraft:stone_hoe";
		case STONE_PICKAXE:
			return "minecraft:stone_pickaxe";
		case STONE_PLATE:
			return "minecraft:stone_pressure_plate";
		case STONE_SLAB2:
			return "minecraft:stone_slab2";
		case STONE_SPADE:
			return "minecraft:stone_shovel";
		case STONE_SWORD:
			return "minecraft:stone_sword";
		case STORAGE_MINECART:
			return "minecraft:chest_minecart";
		case STRING:
			return "minecraft:string";
		case STRUCTURE_BLOCK:
			return "minecraft:structure_block";
		case STRUCTURE_VOID:
			return "minecraft:structure_void";
		case SUGAR:
			return "minecraft:sugar";
		case SUGAR_CANE:
			return "minecraft:reeds";
		case SUGAR_CANE_BLOCK:
			return "minecraft:reeds";
		case SULPHUR:
			return "minecraft:gunpowder";
		case THIN_GLASS:
			return "minecraft:glass_pane";
		case TIPPED_ARROW:
			return "minecraft:tipped_arrow";
		case TNT:
			return "minecraft:tnt";
		case TORCH:
			return "minecraft:torch";
		case TOTEM:
			return "minecraft:totem_of_undying";
		case TRAPPED_CHEST:
			return "minecraft:trapped_chest";
		case TRAP_DOOR:
			return "minecraft:trapdoor";
		case TRIPWIRE:
			return "minecraft:tripwire";
		case TRIPWIRE_HOOK:
			return "minecraft:tripwire_hook";
		case VINE:
			return "minecraft:vine";
		case WALL_BANNER:
			return "minecraft:wall_banner";
		case WALL_SIGN:
			return "minecraft:wall_sign";
		case WATCH:
			return "minecraft:clock";
		case WATER:
			return "minecraft:flowing_water";
		case WATER_BUCKET:
			return "minecraft:water_bucket";
		case WATER_LILY:
			return "minecraft:waterlily";
		case WEB:
			return "minecraft:web";
		case WHEAT:
			return "minecraft:wheat";
		case WHITE_SHULKER_BOX:
			return "minecraft:white_shulker_box";
		case WOOD:
			return "minecraft:planks";
		case WOODEN_DOOR:
			return "minecraft:wooden_door";
		case WOOD_AXE:
			return "minecraft:wooden_axe";
		case WOOD_BUTTON:
			return "minecraft:wooden_button";
		case WOOD_DOOR:
			return "minecraft:wooden_door";
		case WOOD_DOUBLE_STEP:
			return "minecraft:double_wooden_slab";
		case WOOD_HOE:
			return "minecraft:wooden_hoe";
		case WOOD_PICKAXE:
			return "minecraft:wooden_pickaxe";
		case WOOD_PLATE:
			return "minecraft:wooden_pressure_plate";
		case WOOD_SPADE:
			return "minecraft:wooden_shovel";
		case WOOD_STAIRS:
			return "minecraft:oak_stairs";
		case WOOD_STEP:
			return "minecraft:wooden_slab";
		case WOOD_SWORD:
			return "minecraft:wooden_sword";
		case WOOL:
			return "minecraft:wool";
		case WORKBENCH:
			return "minecraft:crafting_table";
		case WRITTEN_BOOK:
			return "minecraft:written_book";
		case YELLOW_FLOWER:
			return "minecraft:yellow_flower";
		case YELLOW_SHULKER_BOX:
			return "minecraft:yellow_shulker_box";
		default:
			return "unknown";
		}
	}
}
